# Generated by Django 3.1.7 on 2021-09-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='Your Username')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Your Full Name')),
                ('user_id', models.CharField(default='', max_length=30, unique=True)),
                ('email', models.EmailField(default='', max_length=15)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
