# Generated by Django 3.1.7 on 2021-09-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=15)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Account Name')),
                ('created_date', models.DateTimeField()),
                ('user_id', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Contact Name')),
                ('email', models.EmailField(default='', max_length=15)),
                ('account_id', models.CharField(default='', max_length=30)),
                ('user_id', models.CharField(default='', max_length=30)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
