# Generated by Django 3.1.7 on 2021-09-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0002_account_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
